### ISSUE TITLE
stuck when comment on table

### ISSUE THREAD

**Issue by anhnhoktvn** [guidesmiths/marv#24]
it's stuck when running migration file (002.comment_table.sql):
```
COMMENT ON TABLE migrations_lock IS 'this is a comment';
```

**Comment by cressie176** [comment]
Hi @anhnhoktvn,
Thanks for posting. Couple of questions...

1. What driver are you using?
2. Is `COMMENT ON TABLE migrations_lock IS 'this is a comment';` the contents of the migration file?

If you are trying to add a comment to the migrations_lock table I wouldn't be surprised if this was blocking since marv will have already locked this table (using a different connection) to ensure migrations aren't run concurrently

**Comment by anhnhoktvn** [comment]
1. postgres
2. yes

Maybe we can note that marv locks some tables while running.

**Comment by cressie176** [comment]
Hi @anhnhoktvn ,

> Maybe we can note that marv locks some tables while running.

Thanks for the suggestion. I'm reluctant to add this to the readme since modifying marv's internal tables isn't something I would expect many users to do and the existing behaviour doesn't break [the principle of least surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) since all robust database/schema migration libraries work by acquiring a lock somehow, and the `migrations_lock` table is descriptively named. Also [Debugging](https://github.com/guidesmiths/marv#debugging) or inspecting the [code](https://github.com/guidesmiths/marv/blob/master/lib/migrate.js#L32-L35) would also reveal that the tables were being locked. 

1. What's the reason for adding a comment to the `migrations_lock` table?
1. Were you aware that you can rename the migrations and migrations_lock tables using the `table` option (Currently not well [documented](https://github.com/guidesmiths/marv#configuring-drivers) - I'll improve this)

**Comment by anhnhoktvn** [comment]
Hi,
 1. I'm using postgraphile to generate graphql service directly from
postgres schema. And I don't want to show some tables in the service (by
add some special comment to those tables).
2. No, but it's not my usecase right now.
I turned on the debug mode but there is nothing show that marv is locking
some tables. However I think I can simply add those comments manually,
that's not a big deal.

**Comment by cressie176** [comment]
> I turned on the debug mode but there is nothing show that marv is locking
some tables.

This is what I see when I run marv with debug enabled. It doesn't show the tables that are being locked (some driver implementations may not lock tables), but does show that locking is occuring.
```
marv:migrate Connecting driver +23ms
marv:migrate Ensuring migrations +0ms
marv:migrate Locking migrations +0ms
...
```

> I'm using postgraphile to generate graphql service directly from
postgres schema. And I don't want to show some tables in the service (by
add some special comment to those tables).

I'm happy to update the marv pg driver to add a comment like `Created by marv@version` or similar.

**Comment by anhnhoktvn** [comment]
ah, I see that in the log.
> I'm happy to update the marv pg driver to add a comment like Created by marv@version or similar.
I think you don't have to. With postgraphile, I have to add a comment like
E'@omit all' (similar to `@MARV SKIP = true`) to the `migrations` and `migrations_lock` tables, to make
postgraphile skip those tables.
Maybe it could be closed now.
