### ISSUE TITLE
Feature idea / comment

### ISSUE THREAD

**Issue by scotthooker** [guidesmiths/marv#35]
Do you think it would be feasible to integrate Marv into something like https://github.com/nijikokun/generate-schema 
Or indeed leverage marv to keep a sql db uptodate with a JSON/ swagger definition ?

**Comment by cressie176** [comment]
Hey @scotthooker,

Sorry, saw this come through then completely forgot about it. 

I would be reluctant to build a direct integration between marv and a JSON=>SQL Schema generator. One of the reasons I wrote marv is because I wanted to specify my change sets in SQL. It also means you end up having to maintain the mapping between JSON and ${INSERT_DB_OF_CHOICE} SQL.

[generate-schema](https://github.com/nijikokun/generate-schema) also looks like it's designed to create a complete schema, rather than a series of changes, which I suspect would make things significantly more difficult.

**Comment by scotthooker** [comment]
Thanks! Makes sense :)
