### ISSUE TITLE
Feature request: events

### ISSUE THREAD

**Issue by raarts** [guidesmiths/marv#40]
(I picked marv for it's simplicity. Great work).

It would sure be nice to be able to plug in your own logging. Events would make that possible.

Thanks a lot for writing this!

**Comment by cressie176** [comment]
Hi @raarts,
Thanks for picking marv, I'm glad you're enjoying it. Good idea around using events as a way to support logging. I've had a quick think about how this could be implemented, and one way would be for marv ([1](https://github.com/guidesmiths/marv/blob/master/api/promise.js#L4-L9), [2](https://github.com/guidesmiths/marv/blob/master/api/callback.js#L1-L6)) to become an instance of [EventEmitter](https://nodejs.org/docs/latest-v16.x/api/events.html#class-eventemitter) instead of a plain object. Then it could be injected into each of the `migrate`, `scan`, `drop` and `parseDirective` functions - assuming they required logging. The resulting user code would look like
```js
marv.on('message', (msg, ctx) => {
  console.log(msg, ctx);
})
```

An alternative solution would be to add an [EventEmitter](https://nodejs.org/docs/latest-v16.x/api/events.html#class-eventemitter) as a property to marv ([1](https://github.com/guidesmiths/marv/blob/master/api/promise.js#L4-L9), [2](https://github.com/guidesmiths/marv/blob/master/api/callback.js#L1-L6)), and pass this in to the functions. The resulting user could would look like
```js
marv.events.on('message', (msg, ctx) => {
  console.log(msg, ctx);
})
```

Yet a third solution would be to use a singleton and simply require it where needed. I'm not overly keen on this solution though as it would make it clumsy to obtain the emitter from one of the drivers since these are in separate packages.

Out of interest what would you liked to log? I guess the migrations being run. Anything else?

**Comment by raarts** [comment]
I use NestJS, and they have their own format for log lines. It would be nice to be able to adhere to that.
So I would like to be able to intercept all errors to write them in the NestJS format.

Thanks for responding.

**Comment by cressie176** [comment]
Hi @raarts, 
Marv doesn't continue on error, instead it yields them either through a callback or by rejecting depending on whether you use a callback or promise api, so in your case you should do something similar to

```js
const migrations = await marv.scan(directory);
try {
  await marv.migrate(migrations, driver({ connection }));
} catch {
  // log error 
}
```
